# This file is a template, and might need editing before it works on your project.
# This is a very simple template that mainly relies on FastLane to build and distribute your app.
# Read more about how to use this template on the blog post https://about.gitlab.com/2019/03/06/ios-publishing-with-gitlab-and-fastlane/
# You will also need fastlane and signing configuration for this to work, along with a MacOS runner.
# These details are provided in the blog post.

# Note that when you're using the shell executor for MacOS builds, the
# build and tests run as the identity of the runner logged in user, directly on
# the build host. This is less secure than using container executors, so please
# take a look at our security implications documentation at
# https://docs.gitlab.com/runner/security/#usage-of-shell-executor for additional
# detail on what to keep in mind in this scenario.

stages:
    - build_beta_uat
    - upload_beta_uat
    - build_beta
    - upload_beta
    - build_release
    - upload_release

variables:
    LC_ALL: 'en_US.UTF-8'
    LANG: 'en_US.UTF-8'
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: recursive

# before_script:
#     - git submodule sync --recursive
#     - git submodule update --init --recursive

build_beta_uat_ipa:
    stage: build_beta_uat
    script:
        - bundle exec fastlane build_ipa code:$CI_COMMIT_REF_NAME export_method:adhoc env:UAT
    artifacts:
        paths:
            - builds/*
    environment:
        name: uat_review
    only:
        - /^build/uat.*$/
    tags:
        - ios

upload_beta_uat_filemanager:
    stage: upload_beta_uat
    script:
        - bundle exec fastlane upload_filemanager code:$CI_COMMIT_REF_NAME export_method:adhoc env:UAT
    dependencies:
        - build_beta_uat_ipa
    environment:
        name: uat_review
    only:
        - /^build/uat.*$/
    tags:
        - ios

build_beta_ipa:
    stage: build_beta
    script:
        - bundle exec fastlane build_ipa code:$CI_COMMIT_REF_NAME export_method:adhoc env:PRO
    artifacts:
        paths:
            - builds/*
    environment:
        name: uat_review
    only:
        - /^build/pro.*$/
    tags:
        - ios

upload_beta_filemanager:
    stage: upload_beta
    script:
        - bundle exec fastlane upload_filemanager code:$CI_COMMIT_REF_NAME export_method:adhoc env:PRO
    dependencies:
        - build_beta_ipa
    environment:
        name: uat_review
    only:
        - /^build/pro.*$/
    tags:
        - ios

build_release_ipa:
    stage: build_release
    script:
        - bundle exec fastlane build_ipa code:$CI_COMMIT_REF_NAME export_method:appstore env:PRO
    artifacts:
        paths:
            - builds/*
    environment:
        name: production
    when: manual
    allow_failure: false
    only:
        - /^build/pro.*$/
    tags:
        - ios

upload_release_filemanager:
    stage: upload_release
    script:
        - bundle exec fastlane upload_filemanager code:$CI_COMMIT_REF_NAME export_method:appstore env:PRO
    dependencies:
        - build_release_ipa
    environment:
        name: production
    only:
        - /^build/pro.*$/
    tags:
        - ios

upload_release_appstore:
    stage: upload_release
    script:
        - bundle exec fastlane upload_appstore code:$CI_COMMIT_REF_NAME export_method:appstore env:PRO
    dependencies:
        - build_release_ipa
    environment:
        name: production
    only:
        - /^build/pro.*$/
    tags:
        - ios
