# This file is a template, and might need editing before it works on your project.
# This is a very simple template that mainly relies on FastLane to build and distribute your app.
# Read more about how to use this template on the blog post https://about.gitlab.com/2019/03/06/ios-publishing-with-gitlab-and-fastlane/
# You will also need fastlane and signing configuration for this to work, along with a MacOS runner.
# These details are provided in the blog post.

# Note that when you're using the shell executor for MacOS builds, the
# build and tests run as the identity of the runner logged in user, directly on
# the build host. This is less secure than using container executors, so please
# take a look at our security implications documentation at
# https://docs.gitlab.com/runner/security/#usage-of-shell-executor for additional
# detail on what to keep in mind in this scenario.

########################################################################################################################################
# Pipelines:
#                                                       [build_adhoc]         [upload_adhoc]                        [build_appstore]         [upload_appstore]
#
# build/ANY_CONFIG_NAME/pro/ANY_BRANCH_NAME:            (build_adhoc_ipa)  →  (upload_adhoc_ipa_to_filemanager)  →  (build_appstore_ipa)  →  (upload_appstore_ipa_to_filemanager)
#                                                                                                                                         ↘  (upload_appstore_ipa_to_appstore)
#
# build/ANY_CONFIG_NAME/appcenter/ANY_BRANCH_NAME:      (build_adhoc_ipa)  →  (upload_adhoc_ipa_to_filemanager)
#                                                                          ↘  (upload_adhoc_ipa_to_appcenter)
#
# build/ANY_CONFIG_NAME/ANY_BUILD_NAME/ANY_BRANCH_NAME: (build_adhoc_ipa)  →  (upload_adhoc_ipa_to_filemanager)
#
########################################################################################################################################

stages:
  - build_adhoc
  - upload_adhoc
  - build_appstore
  - upload_appstore

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - bundle install

build_adhoc_ipa:
  stage: build_adhoc
  script:
    - bundle exec fastlane build_ipa code:$CI_COMMIT_REF_NAME export_method:adhoc
  artifacts:
    paths:
      - builds/*
  environment:
    name: uat
  only:
    - /build\/.*\/.*\/.*$/ # build/ANY_CONFIG_NAME/ANY_BUILD_NAME/ANY_BRANCH_NAME
  tags:
    - ios

upload_adhoc_ipa_to_filemanager:
  stage: upload_adhoc
  script:
    - bundle exec fastlane upload_filemanager code:$CI_COMMIT_REF_NAME export_method:adhoc
  dependencies:
    - build_adhoc_ipa
  environment:
    name: uat
  only:
    - /build\/.*\/.*\/.*$/ # build/ANY_CONFIG_NAME/ANY_BUILD_NAME/ANY_BRANCH_NAME
  tags:
    - ios

upload_adhoc_ipa_to_appcenter:
  stage: upload_adhoc
  script:
    - bundle exec fastlane upload_appcenter code:$CI_COMMIT_REF_NAME export_method:adhoc
  dependencies:
    - build_adhoc_ipa
  environment:
    name: uat
  only:
    - /build\/.*\/appcenter\/.*$/ # build/ANY_CONFIG_NAME/appcenter/ANY_BRANCH_NAME
  tags:
    - ios

build_appstore_ipa:
  stage: build_appstore
  script:
    - bundle exec fastlane build_ipa code:$CI_COMMIT_REF_NAME export_method:appstore
  artifacts:
    paths:
      - builds/*
  environment:
    name: pro
  when: manual
  allow_failure: false
  only:
    - /build\/.*\/pro/.*$/ # build/ANY_CONFIG_NAME/pro/ANY_BRANCH_NAME
  tags:
    - ios

upload_appstore_ipa_to_filemanager:
  stage: upload_appstore
  script:
    - bundle exec fastlane upload_filemanager code:$CI_COMMIT_REF_NAME export_method:appstore
  dependencies:
    - build_appstore_ipa
  environment:
    name: pro
  only:
    - /build\/.*\/pro/.*$/ # build/ANY_CONFIG_NAME/pro/ANY_BRANCH_NAME
  tags:
    - ios

upload_appstore_ipa_to_appstore:
  stage: upload_appstore
  script:
    - bundle exec fastlane upload_appstore code:$CI_COMMIT_REF_NAME export_method:appstore
  dependencies:
    - build_appstore_ipa
  environment:
    name: pro
  only:
    - /build\/.*\/pro/.*$/ # build/ANY_CONFIG_NAME/pro/ANY_BRANCH_NAME
  tags:
    - ios
